fos_rest:
    disable_csrf_role: ROLE_API
    param_fetcher_listener:  true
    routing_loader: true
    service:
        view_handler: fos_rest.view_handler.default
    view:
        view_response_listener: true
        formats:
            rss: true
            xml: true
            json: true
        templating_formats:
            json: false
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        mime_types: {'jsonp': ['application/javascript+jsonp'], 'jsonld': ['application/ld+json']}
    exception:
        enabled: true
        exception_controller: 'App\Controller\ExceptionController::showAction'
    allowed_methods_listener: true
    access_denied_listener:
            json: true
    body_listener: true

