nelmio_cors:
    defaults:
        allow_origin: ["http://localhost:63342"]
        allow_methods: ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
        allow_headers: ["*"]
        expose_headers: ["Link"]
        max_age: 3600
    paths:
        "^/":
            allow_origin: ["http://localhost:8080","https://admin.expago.com","https://expago.com","https://dev.admin.expago.com","https://dev.expago.com"]
            allow_headers: ["*"]
            allow_methods: ["POST", "PUT", "GET", "DELETE", "OPTIONS", "PATCH"]
            expose_headers: ["Link"]
            max_age: 3600