security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    role_hierarchy:
        ROLE_ADMIN: [ROLE_ADMIN, ROLE_EXPERT]
        ROLE_EXPERT: [ROLE_EXPERT, ROLE_USER]
        ROLE_USER: [ROLE_USER]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        users:
          entity: { class: App\Entity\User, property: email }
    encoders:
        App\Entity\User: bcrypt
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin/
            anonymous: true
            guard:
                authenticators:
                    - app.security.login_form_authenticator
            logout:
                path: /admin/logout
            remember_me:
                secret: '%env(secret)%'
                lifetime: 604800
                path: /admin/
        main:
            pattern: ^/
            anonymous: true
            stateless: true
            guard:
                authenticators:
                    - app.security.token_authenticator

    access_control:
            - { path: ^/admin/login/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/, role: ROLE_ADMIN }
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
