#index:
#    path: /
#    controller: App/Controller/DefaultController.php

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

app.swagger_ui:
    path: /api
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

api_v1:
    resource: '../src/Controller/Api'
    defaults: {"_format": json}
    type:     annotation
    prefix:   /

